const stationOverrides = {
    "addison road": "Addison Road-Seat Pleasant",
    "arch-navy mem": "Archives-Navy Memorial-Penn Quarter",
    "archives-navy mem'l": "Archives-Navy Memorial-Penn Quarter",
    "ballston": "Ballston-MU",
    "ballston-mu": "Ballston-MU",
    "benning road": "Benning Road",
    "brookland": "Brookland-CUA",
    "capitol heights": "Capitol Heights",
    "capitol s": "Capitol South",
    "columbia hgts": "Columbia Heights",
    "downtown largo": "Downtown Largo",
    "dulles airport": "Washington Dulles International Airport",
    "dunn loring-merrifield": "Dunn Loring-Merrifield",
    "dupont circle n": "Dupont Circle",
    "dupont circle s": "Dupont Circle",
    "east falls church": "East Falls Church",
    "farragut n nw": "Farragut North",
    "farragut north": "Farragut North",
    "farragut west": "Farragut West",
    "fed center sw": "Federal Center SW",
    "fed triangle": "Federal Triangle",
    "foggy bottom": "Foggy Bottom-GWU",
    "frndshp hgts n": "Friendship Heights",
    "gal pl-chntwn n": "Gallery Pl-Chinatown",
    "gal pl-chntwn s": "Gallery Pl-Chinatown",
    "gal plc-chntn e": "Gallery Pl-Chinatown",
    "gal plc-chntn n": "Gallery Pl-Chinatown",
    "gal plc-chntn s": "Gallery Pl-Chinatown",
    "gal plc-chntn w": "Gallery Pl-Chinatown",
    "greensboro": "Greensboro",
    "grosvenor": "Grosvenor-Strathmore",
    "herndon": "Herndon",
    "huntington n": "Huntington",
    "huntington s": "Huntington",
    "innovation center": "Innovation Center",
    "judiciary sq w": "Judiciary Square",
    "judiciary sq e": "Judiciary Square",
    "l'enfant plaza w": "L'Enfant Plaza",
    "l'enfant plza": "L'Enfant Plaza",
    "l'enfant plza e": "L'Enfant Plaza",
    "l'enfant plza n": "L'Enfant Plaza",
    "l'enfant plza s": "L'Enfant Plaza",
    "l'enfant plza w": "L'Enfant Plaza",
    "largo town center": "Downtown Largo",
    "lenfant plaza": "L'Enfant Plaza",
    "mclean": "McLean",
    "mcpherson sq e": "McPherson Square",
    "medical center": "Medical Center",
    "metro center e": "Metro Center",
    "metro center n": "Metro Center",
    "metro center s": "Metro Center",
    "metro center w": "Metro Center",
    "morgan boulevard": "Morgan Boulevard",
    "mt vern sq-udc": "Mt Vernon Sq 7th St-Convention Center",
    "n bethesda": "North Bethesda",
    "nat airport n": "Ronald Reagan Washington National Airport",
    "nat airport s": "Ronald Reagan Washington National Airport",
    "navy yard e": "Navy Yard-Ballpark",
    "navy yard w": "Navy Yard-Ballpark",
    "noma gallaudet north": "NoMa-Gallaudet U",
    "noma gallaudet south": "NoMa-Gallaudet U",
    "potomac ave": "Potomac Ave",
    "prince georges plaza": "Hyattsville Crossing",
    "reston town center": "Reston Town Center",
    "rhode island ave": "Rhode Island Ave-Brentwood",
    "shaw-hwrd u n": "Shaw-Howard U",
    "shaw-hwrd u s": "Shaw-Howard U",
    "silver spring n": "Silver Spring",
    "silver spring s": "Silver Spring",
    "smithsonian n": "Smithsonian",
    "smithsonian s": "Smithsonian",
    "spring hill": "Spring Hill",
    "stadium-armory": "Stadium-Armory",
    "tysons corner": "Tysons",
    "u st-cardozo e": "U Street/African-Amer Civil War Memorial/Cardozo",
    "u st-cardozo w": "U Street/African-Amer Civil War Memorial/Cardozo",
    "u street-cardozo": "U Street/African-Amer Civil War Memorial/Cardozo",
    "udc-van ness": "Van Ness-UDC",
    "union stn e": "Union Station",
    "union stn n": "Union Station",
    "union stn s": "Union Station",
    "union stn w": "Union Station",
    "vienna/fairfax-gmu": "Vienna/Fairfax-GMU",
    "virginia sq-gmu": "Virginia Square-GMU",
    "w hyattsville": "West Hyattsville",
    "washington dulles international airport": "Washington Dulles International Airport",
    "west falls church-vt/uva": "West Falls Church",
    "white flint": "North Bethesda",
    "wiehle-reston east": "Wiehle-Reston East",
    "woodley park-zoo": "Woodley Park-Zoo/Adams Morgan",
    "anacostia n": "Anacostia",
    "anacostia s": "Anacostia",
    "ga ave-petworth": "Georgia Avenue-Petworth"
};